export const CREATE_PURCHASE = {
	IN_PROGRESS: 'app/Customers/CREATE_PURCHASE/IN_PROGRESS',
	SUCCESS: 'app/Customers/CREATE_PURCHASE/SUCCESS',
	FAILURE: 'app/Customers/CREATE_PURCHASE/FAILURE',
}

export const FETCH_PURCHASES = {
	IN_PROGRESS: 'app/Customers/FETCH_PURCHASES/IN_PROGRESS',
	SUCCESS: 'app/Customers/FETCH_PURCHASES/SUCCESS',
	FAILURE: 'app/Customers/FETCH_PURCHASES/FAILURE',
}

export const MARK_PURCHASE_COMPLETE = {
	IN_PROGRESS: 'app/Customers/MARK_PURCHASE_COMPLETE/IN_PROGRESS',
	SUCCESS: 'app/Customers/MARK_PURCHASE_COMPLETE/SUCCESS',
	FAILURE: 'app/Customers/MARK_PURCHASE_COMPLETE/FAILURE',
}
